version: 2
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: node -v
      - run: npm i -g yarn
      - run: yarn
      - run: yarn run build
  test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: node -v
      - run: npm i -g yarn
      - run: yarn
      - run: yarn run lint
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build

